# Generated by Django 3.2.4 on 2021-06-29 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0008_auto_20210625_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='crsgrade',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='crsgrade',
            name='remarks',
            field=models.CharField(default='Submitted', max_length=150, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 13, 37, 14, 841781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 13, 37, 14, 841781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 13, 37, 14, 841781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 13, 37, 14, 841781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 13, 37, 14, 841781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 13, 37, 14, 841781, tzinfo=utc)),
        ),
    ]
