# Generated by Django 3.2.4 on 2021-06-30 04:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0012_auto_20210630_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyplan',
            name='curricula',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='studentinfo',
        ),
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 18, 20, 704941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 18, 20, 704941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 18, 20, 704941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 18, 20, 704941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 4, 18, 20, 704941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 18, 20, 704941, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='courseList',
        ),
        migrations.DeleteModel(
            name='studyPlan',
        ),
    ]
