# Generated by Django 3.2.4 on 2021-06-30 04:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0013_auto_20210630_1218'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='curricula',
            name='unique_curriculum',
        ),
        migrations.AddField(
            model_name='curricula',
            name='schoolYr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='School Year'),
        ),
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 28, 56, 797262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 28, 56, 797262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 28, 56, 797262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 28, 56, 797262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 4, 28, 56, 797262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 28, 56, 797262, tzinfo=utc)),
        ),
        migrations.AddConstraint(
            model_name='curricula',
            constraint=models.UniqueConstraint(fields=('departmentID', 'cYear', 'cSem', 'schoolYr'), name='unique_curriculum'),
        ),
    ]
