# Generated by Django 3.2.4 on 2021-06-30 04:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0014_auto_20210630_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 37, 19, 887238, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 37, 19, 887238, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 37, 19, 887238, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 37, 19, 887238, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 4, 37, 19, 887238, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 4, 37, 19, 887238, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='studyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissionYr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Admission Year')),
                ('approved', models.BooleanField(default=False)),
                ('curricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRS.curricula', verbose_name='')),
                ('studentinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRS.studentinfo', unique=True, verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='courseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=50, null=True, verbose_name='Course Code')),
                ('courseName', models.CharField(max_length=100, null=True, verbose_name='Course Name')),
                ('courseUnit', models.CharField(max_length=50, null=True, verbose_name='Units')),
                ('prerequisite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pre(Co)-Requisite')),
                ('counted_in_GWA', models.BooleanField(default=True)),
                ('curricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CRS.curricula', verbose_name='Curriculum')),
            ],
        ),
        migrations.AddConstraint(
            model_name='courselist',
            constraint=models.UniqueConstraint(fields=('curricula', 'courseCode'), name='course_outline'),
        ),
    ]
