# Generated by Django 3.2.4 on 2021-06-30 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0016_auto_20210630_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyapplicant',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='facultyinfo',
            name='facultyCitizenship',
            field=models.CharField(default='Filipino', max_length=50, null=True, verbose_name='Citizenship'),
        ),
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 13, 17, 4, 167903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 13, 17, 4, 167903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 13, 17, 4, 167903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 13, 17, 4, 167903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 13, 17, 4, 167903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='studentCitizenship',
            field=models.CharField(default='Filipino', max_length=50, null=True, verbose_name='Citizenship'),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 13, 17, 4, 167903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
