# Generated by Django 3.2.4 on 2021-07-01 03:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0020_auto_20210630_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyearinfo',
            options={'verbose_name_plural': 'Academic Year Information'},
        ),
        migrations.AlterModelOptions(
            name='blocksection',
            options={'verbose_name_plural': 'Block Sections'},
        ),
        migrations.AlterModelOptions(
            name='chairpersoninfo',
            options={'verbose_name_plural': 'Chairperson Information'},
        ),
        migrations.AlterModelOptions(
            name='courselist',
            options={'verbose_name_plural': 'Course Lists'},
        ),
        migrations.AlterModelOptions(
            name='crsgrade',
            options={'verbose_name_plural': 'CRS Grades'},
        ),
        migrations.AlterModelOptions(
            name='currchecklist',
            options={'verbose_name_plural': 'Checklists'},
        ),
        migrations.AlterModelOptions(
            name='curriculuminfo',
            options={'verbose_name_plural': 'Curriculum Information'},
        ),
        migrations.AlterModelOptions(
            name='facultyapplicant',
            options={'verbose_name_plural': 'Faculty Applicants'},
        ),
        migrations.AlterModelOptions(
            name='facultyinfo',
            options={'verbose_name_plural': 'Faculty Information'},
        ),
        migrations.AlterModelOptions(
            name='hd_droppingform',
            options={'verbose_name_plural': 'HD Dropping Form'},
        ),
        migrations.AlterModelOptions(
            name='hdapplicant',
            options={'verbose_name_plural': 'HD Applicants'},
        ),
        migrations.AlterModelOptions(
            name='hdclearanceform',
            options={'verbose_name_plural': 'HD Clearance Forms'},
        ),
        migrations.AlterModelOptions(
            name='hdtransfercert',
            options={'verbose_name_plural': 'HD Transfer Certificate'},
        ),
        migrations.AlterModelOptions(
            name='loaapplicant',
            options={'verbose_name_plural': 'LOA Applicants'},
        ),
        migrations.AlterModelOptions(
            name='ojtapplicant',
            options={'verbose_name_plural': 'OJT Applicants'},
        ),
        migrations.AlterModelOptions(
            name='roominfo',
            options={'verbose_name_plural': 'Room Information'},
        ),
        migrations.AlterModelOptions(
            name='roomschedule',
            options={'verbose_name_plural': 'Room Schedules'},
        ),
        migrations.AlterModelOptions(
            name='shifterapplicant',
            options={'verbose_name_plural': 'Shifter Applicants'},
        ),
        migrations.AlterModelOptions(
            name='spapplicant',
            options={'verbose_name_plural': 'Studyplan Applicants'},
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name_plural': 'Student Information'},
        ),
        migrations.AlterModelOptions(
            name='studentscheduling',
            options={'verbose_name_plural': 'Student Scheduling'},
        ),
        migrations.AlterModelOptions(
            name='studyplan',
            options={'verbose_name_plural': 'Studyplans'},
        ),
        migrations.AlterModelOptions(
            name='subjectinfo',
            options={'verbose_name_plural': 'Subject Information'},
        ),
        migrations.AlterModelOptions(
            name='subjectschedule',
            options={'verbose_name_plural': 'Subject Schedules'},
        ),
        migrations.AlterModelOptions(
            name='transfereeapplicant',
            options={'verbose_name_plural': 'Transferee Applicants'},
        ),
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 3, 11, 5, 813561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 3, 11, 5, 813561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 3, 11, 5, 813561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 3, 11, 5, 813561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 3, 11, 5, 813561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 3, 11, 5, 813561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='middleName',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
