# Generated by Django 3.2.4 on 2021-07-01 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0024_auto_20210701_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculuminfo',
            name='schoolSem',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('Summer', 'Summer')], max_length=100, null=True, verbose_name='School Sem'),
        ),
        migrations.AlterField(
            model_name='curriculuminfo',
            name='schoolYear',
            field=models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=100, null=True, verbose_name='School Year'),
        ),
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 7, 30, 9, 631541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 7, 30, 9, 631541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 7, 30, 9, 631541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 7, 30, 9, 631541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 7, 30, 9, 631541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 7, 30, 9, 631541, tzinfo=utc)),
        ),
    ]
