# Generated by Django 3.2.4 on 2021-07-02 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0031_auto_20210703_0623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studyplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='approved',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='failedsubs',
            field=models.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='courselist',
            name='courseUnit',
            field=models.IntegerField(null=True, verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='curricula',
            name='totalUnits',
            field=models.IntegerField(null=True, verbose_name='Total Units'),
        ),
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 22, 37, 34, 840486, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 22, 37, 34, 840486, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 22, 37, 34, 840486, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 22, 37, 34, 840486, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 22, 37, 34, 840486, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 22, 37, 34, 840486, tzinfo=utc)),
        ),
    ]
