# Generated by Django 3.2.4 on 2021-07-05 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0045_auto_20210706_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyinfo',
            name='facultyIn',
            field=models.CharField(blank=True, default='7 :00', max_length=100, null=True, verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='facultyinfo',
            name='facultyOut',
            field=models.CharField(blank=True, default='22:00', max_length=100, null=True, verbose_name='Time Out'),
        ),
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 18, 18, 51, 775223, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 18, 18, 51, 775223, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 18, 18, 51, 775223, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 18, 18, 51, 775223, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 18, 18, 51, 775223, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 18, 18, 51, 775223, tzinfo=utc)),
        ),
    ]
