# Generated by Django 3.1.5 on 2021-07-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0029_auto_20210703_1330'),
        ('CRS', '0049_auto_20210706_0400'),
    ]

    operations = [
    ]
