# Generated by Django 3.1.5 on 2021-07-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0050_merge_20210706_0429'),
        ('CRS', '0052_auto_20210706_1428'),
    ]

    operations = [
    ]
