# Generated by Django 3.1.5 on 2021-07-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0058_auto_20210706_1746'),
        ('CRS', '0053_merge_20210706_1613'),
    ]

    operations = [
    ]
