# Generated by Django 3.1.5 on 2021-07-08 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0068_auto_20210708_0039'),
        ('CRS', '0059_merge_20210706_1802'),
    ]

    operations = [
    ]
