# Generated by Django 3.2.4 on 2021-07-08 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0069_auto_20210708_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currchecklist',
            name='curriculumCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRS.curriculuminfo', verbose_name='Subjects'),
        ),
        migrations.AlterField(
            model_name='currchecklist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRS.studentinfo', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='currchecklist',
            name='subjectGrades',
            field=models.DecimalField(choices=[(1.0, '1'), (1.25, '1.25'), (1.5, '1.50'), (1.75, '1.75'), (2, '2'), (2.25, '2.25'), (2.5, '2.5'), (2.75, '2.75'), (3.0, '3'), (5.0, '5')], decimal_places=2, max_digits=3, null=True, verbose_name='Subject Grades'),
        ),
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 8, 9, 16, 12, 706591, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 8, 9, 16, 12, 706591, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 8, 9, 16, 12, 706591, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 8, 9, 16, 12, 706591, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 8, 9, 16, 12, 706591, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 8, 9, 16, 12, 706591, tzinfo=utc)),
        ),
    ]
