# Generated by Django 3.1.5 on 2021-07-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0071_auto_20210708_1754'),
        ('CRS', '0070_auto_20210708_1420'),
    ]

    operations = [
    ]
