# Generated by Django 3.2.4 on 2021-07-09 06:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0079_auto_20210709_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominfo',
            name='roomBuilding',
        ),
        migrations.RemoveField(
            model_name='roominfo',
            name='roomNumber',
        ),
        migrations.RemoveField(
            model_name='roominfo',
            name='roomSchedule',
        ),
        migrations.RemoveField(
            model_name='roominfo',
            name='roomType',
        ),
        migrations.AddField(
            model_name='roominfo',
            name='room',
            field=models.CharField(max_length=100, null=True, verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 6, 23, 14, 147941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 6, 23, 14, 147941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 6, 23, 14, 147941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 6, 23, 14, 147941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 6, 23, 14, 147941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studentscheduling',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRS.roominfo', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='studentscheduling',
            name='subjectCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRS.curriculuminfo', verbose_name='Subjects'),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 6, 23, 14, 147941, tzinfo=utc)),
        ),
    ]
