# Generated by Django 3.1.5 on 2021-07-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0079_auto_20210709_1006'),
        ('CRS', '0072_merge_20210708_1825'),
    ]

    operations = [
    ]
