# Generated by Django 3.1.5 on 2021-07-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0080_merge_20210709_1301'),
        ('CRS', '0089_auto_20210709_1918'),
    ]

    operations = [
    ]
