# Generated by Django 3.1.5 on 2021-07-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0092_auto_20210709_2153'),
        ('CRS', '0090_merge_20210709_2022'),
    ]

    operations = [
    ]
